import React from "react";
import UserProvider from "@/providers/UserProvider";
import NotificationProvider from "@/providers/NotificationProvider";
import Navbar from "@/components/layouts/Navbar";
import { getToken } from "@/lib/cookies";
import { apiFetch } from "@/lib/apiFetch";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const token = await getToken();
  const authorizedUser = token ? await apiFetch("GET", "users/me") : null;

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <UserProvider>
          <NotificationProvider>
            <Navbar user={authorizedUser} />
            <div className="xl:max-w-320 max-w-[1024px] mx-auto px-10">
              {children}
            </div>
          </NotificationProvider>
        </UserProvider>
      </body>
    </html>
  );
}
