import React from "react";
import UserProvider from "@/providers/UserProvider";
import NotificationProvider from "@/providers/NotificationProvider";
import Navbar from "@/components/layouts/Navbar";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import apiFetchAuth from "@/lib/apiFetchAuth";
import {SocketProvider} from "@/providers/SocketProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [user, friends, pendingToAccept, pendingToBeAccepted, notifications] = await Promise.all([
    apiFetchAuth("GET", "users/me"),
    apiFetchAuth("GET", "users/friends"),
    apiFetchAuth("GET", "users/pending-to-accept"),
    apiFetchAuth("GET", "users/pending-to-be-accepted"),
    apiFetchAuth("GET", "users/notifications")
  ]);

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <UserProvider user={user} pendingToAccept={pendingToAccept} pendingToBeAccepted={pendingToBeAccepted} friends={friends}>
          <NotificationProvider>
            <SocketProvider user={user}>
              <Navbar user={user} pendingToAccept={pendingToAccept} notifications={notifications} />
              <div className="xl:max-w-320 max-w-[1024px] mx-auto px-10 relative">
                {children}
              </div>
            </SocketProvider>
          </NotificationProvider>
        </UserProvider>
      </body>
    </html>
  );
}
